### PR TITLE
Added ARM32 support

### PR DESCRIPTION
**Pull request by AzazeII**
Adds support for ARM32 as requested by #93 . Not sure how libpty.so will get reviewed, so you are sure it doesn't contain malware code.
I would highly appreciate if this pull request will get merged as i need to use this library for my project targeting ARM platform.
Library was tested on raspberry pi 2 model B revision 1.1, as specified in commit message.
Test code used was as follows:
```java
import com.pty4j.PtyProcess;
import java.util.Map;

public class Test {
	public static void main(String[] args) throws Throwable {
		Map<String, String> env = Map.of("TERM", "xterm");
		PtyProcess process = PtyProcess.exec(args, env);
		process.getInputStream().transferTo(System.out);
	}
}
```
If it's not enough, i can code a better test with piping of PtyProcess streams to JLine3 frontend

### CODE REVIEW

**Comment by AzazeII** [comment]
I will provide better explanation for this pull-request to get more chances for it to be merged.
# Why you should consider merging this PR?
Merging of this pull-request would allow customers who use this library to ship their products with ARM32 support, therefore allowing this library to be used on raspberry pi, orange pi and other ARM32 computers. 

# What this PR adds?
Adds support for ARM32 architecture.

# Screenshots
Successful run of the test (provided in previous comment) on raspberry pi 2 model B 
image

**Comment by segrey** [comment]
Thanks for the PR. I'd like to setup cross-compiling for ARM, because not sure that merging binaries is a good idea. Could you please specify your raspberry pi processor? What's your output of `lscpu` and `uname -a`?

**Comment by AzazeII** [comment]
Architecture:        armv7l
Byte Order:          Little Endian
CPU(s):              4
On-line CPU(s) list: 0-3
Thread(s) per core:  1
Core(s) per socket:  4
Socket(s):           1
Vendor ID:           ARM
Model:               5
Model name:          Cortex-A7
Stepping:            r0p5
CPU max MHz:         900.0000
CPU min MHz:         600.0000
BogoMIPS:            57.60
Flags:               half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm


Linux PostgresPi 5.10.17-v7+ #1414 SMP Fri Apr 30 13:18:35 BST 2021 armv7l GNU/Linux

**Comment by segrey** [comment]
@AzazeII Thanks. Could you please try [arm-binaries](https://github.com/JetBrains/pty4j/tree/arm-binaries) branch and let me know if it works for you? See https://github.com/JetBrains/pty4j/commit/9a702e35ad1077fb930ec657348f06175759e278

**Comment by AzazeII** [comment]
I'll try it right now

**Comment by AzazeII** [comment]
Yeah, it works! Thank you so much.
Just in case(tho i wiped every file from my fork before building arm-binaries branch) i'll leave here md5sum of ARM binary from jar file to ensure it matches binary from the arm-binaries branch
image

**Comment by AzazeII** [comment]
Sorry for bothering, but is there any updates ? Will `arm-binaries` get merged in main branch?

**Comment by segrey** [comment]
@AzazeII Thanks for the information. Merged in master as https://github.com/JetBrains/pty4j/commit/1fd5e571149076b55588e9c870758f8bc993e69d. Closing this PR.

**Comment by AzazeII** [comment]
Thanks!

**Pull request closed without merging**
