### PR TITLE
support linux_riscv64

### PR DESCRIPTION
**Pull request by Glavo**

### CODE REVIEW

**Comment by Glavo** [comment]
@segrey Could you please review this PR?

**Comment by segrey** [comment]
Thanks for the PR. How to build the binary for riscv64 on x64?

**Comment by Glavo** [comment]
> Thanks for the PR. How to build the binary for riscv64 on x64?

@segrey I updated this PR and now it can be built via cross-compilation. (For Ubuntu, the package name is `gcc-riscv64-linux-gnu`)

I built the native files on Ubuntu 22.04 and tested it on the following environment:

```
       _,met$$$$$gg.          glavo@lpi4a
    ,g$$$$$$$$$$$$$$$P.       -----------
  ,g$$P"     """Y$$.".        OS: Debian GNU/Linux 12 (bookworm) riscv64
 ,$$P'              `$$$.     Host: T-HEAD Light Lichee Pi 4A configuration for 16GB DDR board
',$$P       ,ggs.     `$$b:   Kernel: 5.10.113-lpi4a
`d$$'     ,$P"'   .    $$$    Uptime: 47 mins
 $$P      d$'     ,    $$P    Packages: 1775 (dpkg)
 $$:      $$.   -    ,d$$'    Shell: fish 3.6.0
 $$;      Y$b._   _,d$P'      Terminal: /dev/pts/0
 Y$$.    `.`"Y$$$$P"'         CPU: (4)
 `$$b      "-.__              Memory: 1588MiB / 15727MiB
  `Y$$
   `Y$$.
     `$$b.
       `Y$$b.
          `"Y$b._
              `"""
```

**Comment by Glavo** [comment]
@segrey Could you please review this PR again?

**Comment by Glavo** [comment]
@segrey Could you please take another look at this PR?

**Comment by segrey** [comment]
Thanks you! Merged.
`os/linux/riscv64/libpty.so` was built in https://github.com/JetBrains/pty4j/commit/df43bd9430c331117a61d3ab7948a59c140bf5db

**Comment by Glavo** [comment]
> Thank you! Merged. `os/linux/riscv64/libpty.so` was built in [df43bd9](https://github.com/JetBrains/pty4j/commit/df43bd9430c331117a61d3ab7948a59c140bf5db)
> 
> Please let me know if it works for you.

I tested the master branch on Linux RISC-V 64 and all tests passed except `testWindowsHelpersSigned` (Seems to be unrelated to this PR).

**Pull request merged**
