### PR TITLE
Use slf4j instead of log4j (#2)

### PR DESCRIPTION
**Pull request by yole**
This is needed to migrate IntelliJ IDEA away from log4j (https://youtrack.jetbrains.com/issue/IDEA-265069)

### CODE REVIEW

**Review by satsen — APPROVED** [review]

**Comment by satsen** [comment]
You should put `Fixes #2` in the top of the comment to automatically close the issue when the pull request (hopefully) gets merged.

**Review by segrey — APPROVED** [review]

**Comment by segrey** [comment]
Thanks!

**Comment by yole** [comment]
@segrey Could you please publish a release of the library with these changes?

**Comment by segrey** [comment]
@yole Done! Also, jediterm is published now.

**Pull request merged**
