### PR TITLE
faster all-fd close in child

### PR DESCRIPTION
**Pull request by kprintf**
in some specific environments `sysconf(_SC_OPEN_MAX)` may return very huge number, so opening terminal/running tasks in any IDE became too slow (for fdlimit=1073741824 you need to wait about 3 minutes while all close() would be called)

This patch improves close-all logic a bit: instead of bruteforcing, just iterate over /dev/fd, where all used handles are placed

### CODE REVIEW

**Comment by kprintf** [comment]
@segrey

**Comment by mbiebl** [comment]
As an alternative, you might consider `close_range()`
https://lists.debian.org/debian-devel/2024/06/msg00041.html

**Comment by bigfoot547** [comment]
That is a nice syscall, but requires the `_GNU_SOURCE` ftm to be set, which might conflict with the portability goals of the library

**Comment by segrey** [comment]
@kprintf Thanks for the PR. Hopefully, I've improved it a bit in 04685d870fd09371fe8580f664be5aea41de5b2c. I'd appeciate if you could review it and let me know if something requires more attention.

**Pull request closed without merging**
